Removes mips toolchains from the rust CI build
The error we were getting was:
    error: component 'rust-std' for target 'mips*' is unavailable for download for channel '*'

I have not investigated further. These toolchains are 'Tier 3' here:
     https://rust-lang.github.io/rustup-components-history/
which is a likely factor for them being less supported.